apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: details
    app.kubernetes.io/name: details
  name: details

spec:
  ports:
  - port: 8084
    protocol: TCP
  selector:
    app.kubernetes.io/instance: details
    app.kubernetes.io/name: details
  type: ClusterIP
