apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: ratings
    app.kubernetes.io/name: ratings
  name: ratings-v1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: ratings
      app.kubernetes.io/name: ratings
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app.kubernetes.io/instance: ratings
        app.kubernetes.io/name: ratings
        version: v1
    spec:
      containers:
        - args:
            - ratings
            - --config=config/ratings.yaml
          env:
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.version=v1
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://host.docker.internal:4317
            - name: RATINGS_VALUE
              value: "1"
            - name: TZ
              value: Asia/Shanghai
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: CONSUL_HTTP_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: METRICS_LOG_LEVEL
              value: err
          image: cr-cn-beijing.volces.com/coa-samples/bookinfo
          imagePullPolicy: Always
          name: server
          ports:
            - containerPort: 8083
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /app/config
              name: config-volume
      restartPolicy: Always
      serviceAccountName: default
      volumes:
        - configMap:
            defaultMode: 420
            name: ratings
          name: config-volume

