apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: reviews
    app.kubernetes.io/name: reviews
  name: reviews

spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: thrift
  selector:
    app.kubernetes.io/instance: reviews
    app.kubernetes.io/name: reviews
  type: ClusterIP
