apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: reviews
    app.kubernetes.io/name: reviews
  name: reviews-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: reviews
      app.kubernetes.io/name: reviews
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app.kubernetes.io/instance: reviews
        app.kubernetes.io/name: reviews
        version: v1
    spec:
      containers:
        - args:
            - reviews
            - --config=config/reviews.yaml
          env:
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.version=v1
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://host.docker.internal:4317
            - name: ENABLE_RATINGS
              value: "enable"
            - name: TZ
              value: Asia/Shanghai
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: METRICS_LOG_LEVEL
              value: err
            - name: CONSUL_HTTP_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
          image: cr-cn-beijing.volces.com/coa-samples/bookinfo
          imagePullPolicy: Always
          name: server
          ports:
            - containerPort: 8082
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /app/config
              name: config-volume
      restartPolicy: Always
      serviceAccountName: default
      volumes:
        - configMap:
            defaultMode: 420
            name: reviews
          name: config-volume

