apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loop-for-bookinfo
  name: loop-for-bookinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loop-for-bookinfo
  template:
    metadata:
      labels:
        app: loop-for-bookinfo
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - args:
             - 'while true; do curl -H "baggage: env=dev" -v http://productpage:8081/api/v1/products/1 ; sleep 10; done'
#            - 'while true; do curl -v http://productpage:8081/api/v1/products/1 ; sleep 10; done'
          command:
            - /bin/sh
            - -c
            - --
          image: nicolaka/netshoot
          name: loop-for-bookinfo
